name: API pipeline

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DYNAMO_ENDPOINT: "http://localhost:8000"
      AWS_REGION: "us-east-1"
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      PYTHONUNBUFFERED: TRUE

    steps:
      - name: Start dynamodb
        run: docker run -d -p 8000:8000 --name db amazon/dynamodb-local:latest -jar DynamoDBLocal.jar -sharedDb -inMemory

      - name: Checkout commit
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        working-directory: api
        run: make install

      - name: Run linting
        working-directory: api
        run: make lint

      - name: Wait for connection
        working-directory: api
        run: make wait-dynamo

      - name: Run migrations
        working-directory: api
        run: make migrate

      - name: Run tests
        working-directory: api
        run: make test
