name: CI

on: push

jobs:
  Download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout commit
        uses: actions/checkout@v3

  Build:
    runs-on: ubuntu-latest
    needs: Download

    steps:
      - name: Install dependencies
        working-directory: scraper
        run: npm i

      - name: Build app
        working-directory: scraper
        run: npm run build

      - name: Check app is working
        working-directory: scraper
        run: node build/index.js
