name: Cron job scraping session

on:
  schedule:
    - cron: '*/15 * * * *' # Run every day every 15 minutes

jobs:
  Get:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout commit
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        working-directory: scraper
        run: npm i

      - name: Download browsers
        working-directory: scraper
        run: npx puppeteer browsers install firefox && npx puppeteer browsers install chrome

      - name: Build app
        working-directory: scraper
        run: npm run build

      - name: Run scraping session and save data
        working-directory: scraper
        run: node build/index.js
